### ISSUE TITLE
archlinux 运行错误

### ISSUE THREAD

**Issue by justforlxz** [linuxdeepin/deepin-movie#10]
ATTENTION: default value of option bo_reuse overridden by environment.
file:///usr/share/deepin-movie/views/main.qml:69:5: Type PreferenceWindow unavailable 
         PreferenceWindow { id: preference_window } 
         ^
file:///usr/share/deepin-movie/views/PreferenceWindow.qml:285:13: Type SpinnerRow unavailable 
                 SpinnerRow { 
                 ^
file:///usr/share/deepin-movie/views/SpinnerRow.qml:26:2: Type DSpinner unavailable 
        DSpinner { 
        ^
file:///usr/lib/qt/qml/Deepin/Widgets/DSpinner.qml:3:1: Type DTextInput unavailable 
     DTextInput { 
     ^
file:///usr/lib/qt/qml/Deepin/Widgets/DTextInput.qml:191:5: Type DInputActions unavailable 
         DInputActions { 
         ^
file:///usr/lib/qt/qml/Deepin/Widgets/DInputActions.qml:2:1: module "DBus.Com.Deepin.Menu" is not installed 
     import DBus.Com.Deepin.Menu 1.0 
     ^
Traceback (most recent call last):
  File "/usr/bin/deepin-movie", line 107, in <module>
    windowView.initWindowSize()
  File "/usr/share/deepin-movie/views/window.py", line 78, in initWindowSize
    self.rootObject().initWindowSize()
AttributeError: 'NoneType' object has no attribute 'initWindowSize'

是不是我没有包含一些python的库。我记得上次补全以后又出现新的错误了。。

**Comment by 1dot75cm** [comment]
需要先运行 /usr/lib64/deepin-menu 监听， 然后再开另一个终端运行 deepin-movie。
deepin-menu 由 /etc/xdg/autostart/deepin-menu.desktop 开机运行。

**Comment by zhuzilinuser** [comment]
还是不行啊...

**Comment by 1dot75cm** [comment]
http://download.opensuse.org/repositories/home:/metakcahura:/arch-deepin/Arch_Extra/x86_64/

**Comment by felixonmars** [comment]
一楼的错误是因为 deepin-dbus-factory 没有安装。现在这个包在 [community] 仓库也有提供了～

**Comment by BLumia** [comment]
:1st_place_medal:
