### ISSUE TITLE
Peewee assistance

### ISSUE THREAD

**Issue by coleifer** [linuxdeepin/deepin-movie#16]
Hey, I'm the author of peewee and am flattered that you've chosen to use it in your application. I hope it hasn't been a decision that you've regretted, but I can see from some comments that you may have run into issues with it.

Please don't hesitate to let me know if you find a bug, or if the behavior is surprising or counter-intuitive. You can open issues here: https://github.com/coleifer/peewee/issues or feel free to respond in this ticket. I'd be happy to help.

**Comment by manateelazycat** [comment]
thanks for information! 
It's not bug, closed it.
