### ISSUE TITLE
Utf 8 subtitles

### ISSUE THREAD

**Issue by liqen** [linuxdeepin/deepin-movie#18]
Hi,
When I load Portuguese subtitles (have a special characters) it appears misconfigured
I suggest support for UTF 8 subtitles
Thank you so much

**Comment by bruno-sartori** [comment]
+1 for this issue

**Comment by ArthurBugan** [comment]
+1 for this!

**Comment by ademcal** [comment]
I am Turkish user I have same problem.

**Comment by SMMousaviSP** [comment]
I have same problem for Persian (Farsi)

**Comment by SMMousaviSP** [comment]
The problem will solve if you download a font that supports your language and set that font for showing subtitles in setting(sorry for bad English)
