### ISSUE TITLE
OpenGL module import not necessary

### ISSUE THREAD

**Issue by jefbed** [linuxdeepin/deepin-movie#19]
Hello.  While testing deepin-movie on Arch linux, I've found one issue:
This is not necessary:
src/main.py, line 43:
`from OpenGL import GL`
It is not used in the file. And it introduces a dependency on python2-opengl unnecessarily.
After commenting out this line, I'm able to run deepin-movie.
Please see: [Arch Linux bug 52108](https://bugs.archlinux.org/task/52108)
Regards

**Comment by hualet** [comment]
@liujianfeng

**Comment by amazingfate** [comment]
There is  a bug of pyqt: https://bugs.launchpad.net/ubuntu/+source/python-qt4/+bug/941826
So deepin-movie import opengl from python

**Comment by jefbed** [comment]
So, without this import, no hardware acceleration is available with nvidia? I'm using the kms intel i915 driver on sandybridge without this import successfully (maybe the cited issue is fixed in the newest pyqt?).  I don't have any nvidia hardware on which to test, so marking as closed.  The Arch package will simply have to depend upon python2-opengl.
