### ISSUE TITLE
建议空格键暂停时，只出现中间播放按钮，无需出现标题栏和控制栏。鼠标移上再出现

### ISSUE THREAD

**Issue by jay763190097** [linuxdeepin/deepin-movie#34]
提过的bug还没等老王修复，他就离开了。。。。。心塞
在这里记下了，希望deepin越来越好

**Comment by BLumia** [comment]
转到 linuxdeepin/developer-center#2431 处理。

ps. 这功能应该是推迟了吧，目前的开发计划里没排上，大概被放到后面了。
