### ISSUE TITLE
deepin-movie播放samba中视频触发文件复制

### ISSUE THREAD

**Issue by eaglexiang** [linuxdeepin/deepin-movie#35]
项 | 描述
---|---
环境 | Manjaro KDE
视频源 | 内网Samba服务器
打开方式 | 通过文件浏览器打开
deepin-movie表现 | 首先会启动系统的复制，将Samba里的视频复制到本地，然后再播放视频
vlc表现 | 正常直接播放视频
如果手动复制smb://*地址进入deepin-movie | 正常直接播放视频

**Comment by BLumia** [comment]
应该是gvfs的表现，不是影院的问题。

建议直接粘贴 `smb://` URL 使用。
