### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/deepin-movie#36]
Deepin Movie uses a lot of CPU.

Please fix it as soon as possible.

My specs:
Distro: Arch Linux
Graphics: Intel Haswell
CPU: Intel Core i5 4th generation

**Comment by michael-lagotin** [comment]
I use deepin os with i7 6500  u which is a dual core cpu and i have around 3-4 precent usage when using the deepin movie the problem is most certinaly is the arch linux itself and not the app.

**Comment by abijahm** [comment]
i have a i7 4600u on deepin os and the cpu usage is around 25 percent compared to mpv and vlc less than 4 percent probably hardware acceleration is not enabled

**Comment by abijahm** [comment]
passing the location of mpv config with hwdec=vaapi solves the issue
deepin-movie -o ~/.config/mpv/mpv.conf
