### ISSUE TITLE
where is deepin-generate-mo in Makefile

### ISSUE THREAD

**Issue by oracleyue** [linuxdeepin/deepin-movie#8]
It is my first time to install deepin products. I have no idea which deepin package offers this tool. I use Arch Linux. Could you list dependencies in README? 

By the way, when I try to run main.py directly, it implies "import xcb" fail. When I installed python2-xcffib, the module "xcb" was still not found, until I installed the old "xpyb". Could you also list the python package dependencies? (I have qt5, pyqt5, sip installed from arch repo.) I think it would be much helpful for its propagation!

Thank you very much!!

**Comment by snyh** [comment]
dependecies can be found in control file. https://github.com/linuxdeepin/deepin-movie/blob/release/2.2/debian/control

There also has an arch-deepin project https://github.com/fasheng/arch-deepin

**Comment by oracleyue** [comment]
Thanks a lot!!
