### ISSUE TITLE
最后一步编译出错

### ISSUE THREAD

**Issue by fzitou** [linuxdeepin/deepin-movie#9]
fzitou@fzitou-faith ~/PyQt-gpl-5.1.1 $  make
cd qpy/ && ( test -e Makefile || /home/fzitou/Qt5.1.1/5.1.1/gcc_64/bin/qmake /home/fzitou/PyQt-gpl-5.1.1/qpy/qpy.pro -o Makefile ) && make -f Makefile 
make[1]: 正在进入目录 `/home/fzitou/PyQt-gpl-5.1.1/qpy'
cd QtCore/ && ( test -e Makefile || /home/fzitou/Qt5.1.1/5.1.1/gcc_64/bin/qmake /home/fzitou/PyQt-gpl-5.1.1/qpy/QtCore/QtCore.pro -o Makefile ) && make -f Makefile 
make[2]: 正在进入目录`/home/fzitou/PyQt-gpl-5.1.1/qpy/QtCore'
g++ -c -pipe -fno-strict-aliasing -O2 -fPIC -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_CORE_LIB -I../../../Qt5.1.1/5.1.1/gcc_64/mkspecs/linux-g++ -I. -I. -I../../QtCore -I/usr/local/include/python2.7 -I../../../Qt5.1.1/5.1.1/gcc_64/include -I../../../Qt5.1.1/5.1.1/gcc_64/include/QtCore -I. -o qpycore_chimera.o qpycore_chimera.cpp
qpycore_chimera.cpp:21:20: 致命错误：Python.h：没有那个文件或目录
编译中断。
make[2]: **\* [qpycore_chimera.o] 错误 1
make[2]:正在离开目录 `/home/fzitou/PyQt-gpl-5.1.1/qpy/QtCore'
make[1]: *** [sub-QtCore-make_first] 错误 2
make[1]:正在离开目录`/home/fzitou/PyQt-gpl-5.1.1/qpy'
make: **\* [sub-qpy-make_first-ordered] 错误 2

linuxmint17 ×64

**Comment by snyh** [comment]
没装依赖。。。。    mint下没有打好的包吗？
自己编译的话，把基本的依赖装上吧。 

看https://github.com/linuxdeepin/deepin-movie/blob/master/debian/control 文件里面写的

以及阅读https://github.com/linuxdeepin/deepin-movie/blob/master/README
